package com.google.android.gms.internal.ads;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import com.google.android.gms.ads.internal.client.u4;
import com.google.android.gms.ads.internal.client.w2;
import com.google.android.gms.ads.internal.client.z4;
import i5.a;
import i5.c;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/* compiled from: com.google.android.gms:play-services-ads@@22.0.0 */
public final class zzbso extends a {
    public static final Parcelable.Creator<zzbso> CREATOR = new zzbsp();
    public final long zzA;
    public final String zzB;
    public final float zzC;
    public final int zzD;
    public final int zzE;
    public final boolean zzF;
    public final String zzG;
    public final boolean zzH;
    public final String zzI;
    public final boolean zzJ;
    public final int zzK;
    public final Bundle zzL;
    public final String zzM;
    public final w2 zzN;
    public final boolean zzO;
    public final Bundle zzP;
    public final String zzQ;
    public final String zzR;
    public final String zzS;
    public final boolean zzT;
    public final List zzU;
    public final String zzV;
    public final List zzW;
    public final int zzX;
    public final boolean zzY;
    public final boolean zzZ;
    public final int zza;
    public final boolean zzaa;
    public final ArrayList zzab;
    public final String zzac;
    public final zzbjx zzad;
    public final String zzae;
    public final Bundle zzaf;
    public final Bundle zzb;
    public final u4 zzc;
    public final z4 zzd;
    public final String zze;
    public final ApplicationInfo zzf;
    public final PackageInfo zzg;
    public final String zzh;
    public final String zzi;
    public final String zzj;
    public final zzbzg zzk;
    public final Bundle zzl;
    public final int zzm;
    public final List zzn;
    public final Bundle zzo;
    public final boolean zzp;
    public final int zzq;
    public final int zzr;
    public final float zzs;
    public final String zzt;
    public final long zzu;
    public final String zzv;
    public final List zzw;
    public final String zzx;
    public final zzbdl zzy;
    public final List zzz;

    zzbso(int i10, Bundle bundle, u4 u4Var, z4 z4Var, String str, ApplicationInfo applicationInfo, PackageInfo packageInfo, String str2, String str3, String str4, zzbzg zzbzg, Bundle bundle2, int i11, List list, Bundle bundle3, boolean z10, int i12, int i13, float f10, String str5, long j10, String str6, List list2, String str7, zzbdl zzbdl, List list3, long j11, String str8, float f11, boolean z11, int i14, int i15, boolean z12, String str9, String str10, boolean z13, int i16, Bundle bundle4, String str11, w2 w2Var, boolean z14, Bundle bundle5, String str12, String str13, String str14, boolean z15, List list4, String str15, List list5, int i17, boolean z16, boolean z17, boolean z18, ArrayList arrayList, String str16, zzbjx zzbjx, String str17, Bundle bundle6) {
        List list6;
        List list7;
        this.zza = i10;
        this.zzb = bundle;
        this.zzc = u4Var;
        this.zzd = z4Var;
        this.zze = str;
        this.zzf = applicationInfo;
        this.zzg = packageInfo;
        this.zzh = str2;
        this.zzi = str3;
        this.zzj = str4;
        this.zzk = zzbzg;
        this.zzl = bundle2;
        this.zzm = i11;
        this.zzn = list;
        if (list3 == null) {
            list6 = Collections.emptyList();
        } else {
            list6 = Collections.unmodifiableList(list3);
        }
        this.zzz = list6;
        this.zzo = bundle3;
        this.zzp = z10;
        this.zzq = i12;
        this.zzr = i13;
        this.zzs = f10;
        this.zzt = str5;
        this.zzu = j10;
        this.zzv = str6;
        if (list2 == null) {
            list7 = Collections.emptyList();
        } else {
            list7 = Collections.unmodifiableList(list2);
        }
        this.zzw = list7;
        this.zzx = str7;
        this.zzy = zzbdl;
        this.zzA = j11;
        this.zzB = str8;
        this.zzC = f11;
        this.zzH = z11;
        this.zzD = i14;
        this.zzE = i15;
        this.zzF = z12;
        this.zzG = str9;
        this.zzI = str10;
        this.zzJ = z13;
        this.zzK = i16;
        this.zzL = bundle4;
        this.zzM = str11;
        this.zzN = w2Var;
        this.zzO = z14;
        this.zzP = bundle5;
        this.zzQ = str12;
        this.zzR = str13;
        this.zzS = str14;
        this.zzT = z15;
        this.zzU = list4;
        this.zzV = str15;
        this.zzW = list5;
        this.zzX = i17;
        this.zzY = z16;
        this.zzZ = z17;
        this.zzaa = z18;
        this.zzab = arrayList;
        this.zzac = str16;
        this.zzad = zzbjx;
        this.zzae = str17;
        this.zzaf = bundle6;
    }

    public final void writeToParcel(Parcel parcel, int i10) {
        int a10 = c.a(parcel);
        c.k(parcel, 1, this.zza);
        c.e(parcel, 2, this.zzb, false);
        c.p(parcel, 3, this.zzc, i10, false);
        c.p(parcel, 4, this.zzd, i10, false);
        c.q(parcel, 5, this.zze, false);
        c.p(parcel, 6, this.zzf, i10, false);
        c.p(parcel, 7, this.zzg, i10, false);
        c.q(parcel, 8, this.zzh, false);
        c.q(parcel, 9, this.zzi, false);
        c.q(parcel, 10, this.zzj, false);
        c.p(parcel, 11, this.zzk, i10, false);
        c.e(parcel, 12, this.zzl, false);
        c.k(parcel, 13, this.zzm);
        c.s(parcel, 14, this.zzn, false);
        c.e(parcel, 15, this.zzo, false);
        c.c(parcel, 16, this.zzp);
        c.k(parcel, 18, this.zzq);
        c.k(parcel, 19, this.zzr);
        c.h(parcel, 20, this.zzs);
        c.q(parcel, 21, this.zzt, false);
        c.n(parcel, 25, this.zzu);
        c.q(parcel, 26, this.zzv, false);
        c.s(parcel, 27, this.zzw, false);
        c.q(parcel, 28, this.zzx, false);
        c.p(parcel, 29, this.zzy, i10, false);
        c.s(parcel, 30, this.zzz, false);
        c.n(parcel, 31, this.zzA);
        c.q(parcel, 33, this.zzB, false);
        c.h(parcel, 34, this.zzC);
        c.k(parcel, 35, this.zzD);
        c.k(parcel, 36, this.zzE);
        c.c(parcel, 37, this.zzF);
        c.q(parcel, 39, this.zzG, false);
        c.c(parcel, 40, this.zzH);
        c.q(parcel, 41, this.zzI, false);
        c.c(parcel, 42, this.zzJ);
        c.k(parcel, 43, this.zzK);
        c.e(parcel, 44, this.zzL, false);
        c.q(parcel, 45, this.zzM, false);
        c.p(parcel, 46, this.zzN, i10, false);
        c.c(parcel, 47, this.zzO);
        c.e(parcel, 48, this.zzP, false);
        c.q(parcel, 49, this.zzQ, false);
        c.q(parcel, 50, this.zzR, false);
        c.q(parcel, 51, this.zzS, false);
        c.c(parcel, 52, this.zzT);
        c.m(parcel, 53, this.zzU, false);
        c.q(parcel, 54, this.zzV, false);
        c.s(parcel, 55, this.zzW, false);
        c.k(parcel, 56, this.zzX);
        c.c(parcel, 57, this.zzY);
        c.c(parcel, 58, this.zzZ);
        c.c(parcel, 59, this.zzaa);
        c.s(parcel, 60, this.zzab, false);
        c.q(parcel, 61, this.zzac, false);
        c.p(parcel, 63, this.zzad, i10, false);
        c.q(parcel, 64, this.zzae, false);
        c.e(parcel, 65, this.zzaf, false);
        c.b(parcel, a10);
    }
}
